package com.fleetsync.fleetsync.trip;

import java.time.LocalDateTime;

/**
 * Trip — an immutable data record representing a row in the "trips" database table.
 *
 * A trip is an assignment that links one driver to one vehicle for a specific journey.
 * It tracks the full lifecycle of the journey from scheduling to completion.
 *
 * Each field maps directly to a column in the trips table.
 */
public record Trip(

    /** Primary key — auto-generated by the database. */
    Long id,

    /**
     * Foreign key referencing the drivers table (drivers.id).
     * Identifies which driver is assigned to this trip.
     */
    Long driverId,

    /**
     * Foreign key referencing the vehicles table (vehicles.id).
     * Identifies which vehicle is used for this trip.
     */
    Long vehicleId,

    /** The starting location of the trip (e.g. "Karachi Warehouse"). */
    String origin,

    /** The ending location of the trip (e.g. "Lahore Distribution Center"). */
    String destination,

    /**
     * Current lifecycle status of the trip.
     * Valid values and transitions:
     *   SCHEDULED   → IN_PROGRESS  (driver starts the trip)
     *   SCHEDULED   → CANCELLED    (trip is cancelled before starting)
     *   IN_PROGRESS → COMPLETED    (trip finishes successfully)
     *   IN_PROGRESS → CANCELLED    (trip is cancelled mid-way)
     * COMPLETED and CANCELLED are terminal — no further transitions allowed.
     */
    String status,

    /**
     * Timestamp of when the trip moved to IN_PROGRESS status.
     * Null until the trip actually starts.
     */
    LocalDateTime startTime,

    /**
     * Timestamp of when the trip reached COMPLETED or CANCELLED status.
     * Null until the trip ends.
     */
    LocalDateTime endTime,

    /** Timestamp of when this trip record was created — set automatically by the DB. */
    LocalDateTime createdAt
) {}
