package com.fleetsync.fleetsync.vehicle;

import java.time.LocalDateTime;

/**
 * Vehicle — an immutable data record representing a row in the "vehicles" database table.
 *
 * This record is used as the response model when returning vehicle data to the client.
 * Each field maps directly to a column in the vehicles table.
 *
 * Java records auto-generate: constructor, getters (e.g. id(), name()), equals(), hashCode(), toString().
 */
public record Vehicle(

    /** Primary key — auto-generated by the database. */
    Long id,

    /** Human-readable name of the vehicle (e.g. "Truck Alpha", "Van 01"). */
    String name,

    /**
     * Category/type of the vehicle.
     * Examples: "Mini Van", "Cargo Van", "Pickup Truck", "Box Truck"
     */
    String type,

    /**
     * Unique license plate number of the vehicle.
     * Enforced as unique in the database and validated in VehicleController.
     */
    String plateNumber,

    /**
     * Maximum load or passenger capacity of the vehicle.
     * The unit depends on the vehicle type (e.g. kg for cargo, seats for passenger vans).
     */
    int capacity,

    /**
     * Type of fuel the vehicle uses.
     * Examples: "Petrol", "Diesel", "Electric", "Hybrid"
     */
    String fuelType,

    /**
     * Current operational status of the vehicle.
     * Possible values:
     *   - "AVAILABLE" → vehicle is free and can be assigned to a trip
     *   - "ON_TRIP"   → vehicle is currently assigned to an active trip
     * Status is updated automatically when trips are created or completed.
     */
    String status,

    /** Timestamp of when this vehicle was added to the fleet — set automatically by the DB. */
    LocalDateTime createdAt
) {}
