package com.fleetsync.fleetsync.maintenance;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Maintenance — an immutable data record representing a row in the "maintenance" database table.
 *
 * Each maintenance record logs a service event for a specific vehicle.
 * It also stores scheduling information for the NEXT service (date-based or mileage-based),
 * which is used by the /upcoming and /alerts endpoints.
 *
 * Each field maps directly to a column in the maintenance table.
 */
public record Maintenance(

    /** Primary key — auto-generated by the database. */
    Long id,

    /**
     * Foreign key referencing the vehicles table (vehicles.id).
     * Identifies which vehicle this maintenance record belongs to.
     */
    Long vehicleId,

    /** The date on which this maintenance was performed. */
    LocalDate date,

    /**
     * The type/category of maintenance performed.
     * Examples: "OIL_CHANGE", "TIRE_ROTATION", "BRAKE_INSPECTION", "ENGINE_SERVICE"
     */
    String type,

    /**
     * Optional free-text description of the work done.
     * Can be null if no additional details were provided.
     */
    String description,

    /**
     * The cost of this maintenance in currency units.
     * BigDecimal is used instead of double/float to avoid floating-point precision issues
     * when dealing with money values.
     */
    BigDecimal cost,

    /**
     * Optional: the scheduled date for the next service.
     * Used by the /upcoming and /alerts endpoints to surface time-based maintenance reminders.
     * Can be null if no next service date was set.
     */
    LocalDate nextServiceDate,

    /**
     * Optional: the odometer reading (mileage) at which the next service is due.
     * Used by the /upcoming endpoint when currentMileage is provided.
     * Can be null if no mileage-based schedule was set.
     */
    Integer nextServiceMileage,

    /** Timestamp of when this maintenance record was created — set automatically by the DB. */
    LocalDateTime createdAt
) {}
