package com.fleetsync.fleetsync.service;

import com.fleetsync.fleetsync.dto.DriverRequestDto;
import com.fleetsync.fleetsync.dto.DriverResponseDto;
import com.fleetsync.fleetsync.entity.Driver;
import com.fleetsync.fleetsync.entity.User;
import com.fleetsync.fleetsync.repository.DriverRepository;
import com.fleetsync.fleetsync.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * DriverService handles all business logic related to drivers.
 *
 * @Service  — tells Spring this is a service bean; Spring will create and manage its instance.
 * @Transactional — wraps every public method in a database transaction automatically.
 *                  If anything throws an exception, the transaction rolls back so no partial
 *                  data is saved to the database.
 * @RequiredArgsConstructor — Lombok generates a constructor that injects all 'final' fields.
 *                            This is the recommended way to do dependency injection in Spring.
 */
@Service
@Transactional
@RequiredArgsConstructor
public class DriverService {

    // Spring injects these repositories automatically via the constructor generated by @RequiredArgsConstructor.
    // Repositories are the layer that talks directly to the database.
    private final DriverRepository driverRepository;
    private final UserRepository userRepository;

    /**
     * Creates a new driver and saves them to the database.
     *
     * Step-by-step:
     * 1. Check if a driver with the same phone number OR license number already exists.
     *    - We do this because both fields are unique in the database (see Driver entity).
     *    - If a duplicate is found, we throw an exception immediately — no point going further.
     * 2. Look up the User account that will be linked to this driver.
     *    - Every driver must be tied to a User (for login purposes).
     *    - If the userId from the request doesn't match any user, we throw an exception.
     * 3. Build the Driver entity using the builder pattern (provided by Lombok @Builder on Driver).
     *    - We set isActive = true by default because a newly created driver is active.
     * 4. Save the driver to the database using the repository.
     * 5. Convert the saved driver to a DriverResponseDto and return it.
     *    - We never return the raw entity to the outside world — DTOs protect internal structure.
     */
    public DriverResponseDto createDriver(DriverRequestDto req) {
        // Guard clause: reject duplicates before touching the database further
        if (driverRepository.existsByPhoneNumber(req.getPhoneNumber()) ||
            driverRepository.existsByLicenseNumber(req.getLicenseNumber())) {
            throw new IllegalArgumentException("Driver with this phone number or license already exists");
        }

        // Fetch the linked User — orElseThrow means: if not found, throw this exception
        User user = userRepository.findById(req.getUserId())
                .orElseThrow(() -> new IllegalArgumentException("User not found with id: " + req.getUserId()));

        // Build the Driver entity from the incoming request data
        Driver driver = Driver.builder()
                .firstName(req.getFirstName())
                .lastName(req.getLastName())
                .licenseNumber(req.getLicenseNumber())
                .phoneNumber(req.getPhoneNumber())
                .licenseExpiry(req.getLicenseExpiry())
                .user(user)
                .isActive(true)
                .build();

        // save() persists the entity to the DB and returns the saved version (with generated ID)
        Driver saved = driverRepository.save(driver);
        return toDto(saved);
    }

    /**
     * Returns a list of ALL drivers in the system.
     *
     * Step-by-step:
     * 1. findAll() fetches every row from the drivers table.
     * 2. We stream the list — stream() lets us process each item one by one using functional style.
     * 3. map(this::toDto) converts each Driver entity into a DriverResponseDto.
     *    - 'this::toDto' is a method reference — shorthand for driver -> toDto(driver).
     * 4. toList() collects all the converted DTOs back into a List and returns it.
     */
    public List<DriverResponseDto> getAllDrivers() {
        return driverRepository.findAll()
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     *
     * Step-by-step:
     * 1. findById(id) queries the DB for a driver with that ID.
     *    - It returns an Optional<Driver> — either the driver is there or it's empty.
     * 2. orElseThrow() unwraps the Optional — if empty, it throws ResourceNotFoundException.
     * 3. We convert the found Driver entity to a DriverResponseDto and return it.
     */
    public DriverResponseDto getDriverById(Long id) {
        Driver driver = driverRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Driver not found with id: " + id));
        return toDto(driver);
    }

    /**
     * Returns only the drivers that are currently active (isActive = true).
     * 1. findByIsActive(true) is a Spring Data JPA derived query — Spring auto-generates
     *    the SQL: SELECT * FROM drivers WHERE is_active = true
     * 2. We stream and map each result to a DTO, same as getAllDrivers().
     */
    public List<DriverResponseDto> getActiveDrivers() {
        return driverRepository.findByIsActive(true)
                .stream()
                .map(this::toDto)
                .toList();
    }

    public DriverResponseDto updateDriver(Long id, DriverRequestDto req) {
        Driver driver = driverRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Driver not found with id: " + id));

        driver.setFirstName(req.getFirstName());
        driver.setLastName(req.getLastName());
        driver.setPhoneNumber(req.getPhoneNumber());
        driver.setLicenseNumber(req.getLicenseNumber());
        driver.setLicenseExpiry(req.getLicenseExpiry());

        // No save() needed — @Transactional dirty checking auto-flushes the changes
        return toDto(driver);
    }


    public void deactivateDriver(Long id) {
        Driver driver = driverRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Driver not found with id: " + id));

        driver.setIsActive(false);
        // Hibernate will issue: UPDATE drivers SET is_active = false WHERE id = ?
    }


    private DriverResponseDto toDto(Driver driver) {
        return DriverResponseDto.builder()
                .id(driver.getId())
                .firstName(driver.getFirstName())
                .lastName(driver.getLastName())
                .licenseNumber(driver.getLicenseNumber())
                .phoneNumber(driver.getPhoneNumber())
                .licenseExpiry(driver.getLicenseExpiry())
                .isActive(driver.getIsActive())
                .build();
    }
}
