package com.fleetsync.fleetsync.driver;

import java.time.LocalDateTime;

/**
 * Driver — an immutable data record representing a row in the "drivers" database table.
 *
 * Used as the response model when returning driver data to the client.
 * Each field maps directly to a column in the drivers table.
 *
 * Note: A Driver is a person registered in the fleet system.
 * A User is a login account. These are separate — a driver may or may not have a login account.
 */
public record Driver(

    /** Primary key — auto-generated by the database. */
    Long id,

    /** Full legal name of the driver (e.g. "John Smith"). */
    String fullName,

    /**
     * Unique driving license number issued by the transport authority.
     * Enforced as unique in the database and validated in DriverController.
     */
    String licenseNumber,

    /** Driver's contact phone number. */
    String phone,

    /**
     * Driver's email address.
     * Enforced as unique — used for contact and identification.
     */
    String email,

    /**
     * Current assignment status of the driver.
     * Possible values:
     *   - "AVAILABLE" → driver is free and can be assigned to a trip
     *   - "ON_TRIP"   → driver is currently on an active trip
     * Status is updated automatically when trips are created or completed.
     */
    String status,

    /** Timestamp of when this driver was registered — set automatically by the DB. */
    LocalDateTime createdAt
) {}
