package com.fleetsync.fleetsync.user;

import java.time.LocalDateTime;

/**
 * User — an immutable data record representing a row in the "users" database table.
 *
 * Java records (introduced in Java 16) are a concise way to create classes that:
 *   - Hold data (like a DTO or model)
 *   - Are immutable (all fields are final)
 *   - Auto-generate constructor, getters, equals(), hashCode(), and toString()
 *
 * Each field below maps directly to a column in the users table.
 * This record is used when reading user data from the database (e.g. during login).
 *
 * NOTE: Passwords are NEVER stored as plain text — only the BCrypt hash is stored.
 */
public record User(

    /** Primary key — auto-generated by the database (BIGINT AUTO_INCREMENT). */
    Long id,

    /** Unique login name chosen by the user during registration. */
    String username,

    /** Unique email address of the user. */
    String email,

    /**
     * BCrypt hash of the user's password.
     * This is what gets stored in the DB and compared during login.
     * The original plain-text password is never stored.
     */
    String passwordHash,

    /**
     * The user's role in the system — controls what they can access.
     * Allowed values: "MANAGER" or "DRIVER"
     *   - MANAGER: full access to all endpoints
     *   - DRIVER:  can only view trips and update trip status
     */
    String role,

    /** Timestamp of when this user account was created — set automatically by the DB. */
    LocalDateTime createdAt
) {}
